### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by dhananjayWaghela** [firebase/friendlychat-web#118]
We have integrated push notification functionality in application but we are unable to get notification.
So plzz help me

**Comment by nicolasgarnier** [comment]
Hey!

We've split up this repo in three. One for each platform. If your issue is still valid please reopen in the appropriate repo which are:

 - https://github.com/firebase/friendlychat-web
 - https://github.com/firebase/friendlychat-android
 - https://github.com/firebase/friendlychat-ios
