### ISSUE TITLE
Send Image Messages (iOS Swift) fails

### ISSUE THREAD

**Issue by ranesr** [firebase/friendlychat-web#132]
I followed Firebase iOS Codelab Swift - Step 8
https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#8

I was using xcode 8.2. While testing sending image messages on simulator, I clicked the "add a photo" icon, and selected an image. Instead of uploading that image, I got the following error message:

**[Generic] Creating an image format with an unknown type is an error
Error uploading: An unknown error occurred, please check the server response.**

**Comment by iulukaya** [comment]
I believe I addressed this earlier. Can you check it again?

**Comment by dssp100** [comment]
I have the same issue. Is it an issue with Firebase or one with the code in X code?

**Comment by pcragone** [comment]
FYI this is still a problem

**Comment by slgraff** [comment]
Yes, experiencing this as well when I go through the same tutorial.

**Comment by huckphin** [comment]
I am also going through the Swift tutorial right now. I ran into the same issue and wanted to understand more about this problem.

As I was adding some debugging statements to determine what was happening, the callback on _sendMessage_ completed, and it worked! It took a long time, though. I timed it: took me thirty seconds. Seems related to Internet connection speeds and sample image sizes.

**Comment by huckphin** [comment]
I still do get the log message, but it seems to be an innocuous log message, which seems to indicate that it did fail, BTW. That caught me as well.

**Comment by ranesr** [comment]
@iulukaya I checked it again today. But, it still shows the generic message I have written above.

**[Generic] Creating an image format with an unknown type is an error**

But, I do not see this message-

**Error uploading: An unknown error occurred, please check the server response.**

So, I thought it uploaded image; and when I checked the storage item in my project in Firebase console, it shows that the file is uploaded to the bucket.

In the simulator, I also see a new message for the uploaded image,

sent by: Optional("my-username")

**Comment by ulukaya** [comment]
If the issue still exist please report at https://github.com/firebase/friendlychat-ios/issues
