### ISSUE TITLE
IntentService has ambiguous method

### ISSUE THREAD

**Issue by IgorGanapolsky** [firebase/friendlychat-web#136]
Your codelab says:
> Note: It helps to add an IntentService that establishes a base index of all messages for you initially. See details in the App Indexing documentation.

However, **AppIndexingService** just has an ambiguous method: `getAllRecipes()`.  It is not clear what to do with this method, or what your codelab meant for the users to put into IntentService above.

Also, what does 
> base index of all messages 

actually mean?  Does Firebase work faster with indexes, just like Oracle and SqlServer do?

Can you please explain?

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#9
