### ISSUE TITLE
Image sending in android-starter

### ISSUE THREAD

**Issue by salimshivani** [firebase/friendlychat-web#164]
There is an issue in android-starter in sending an image. When the image is sent, either the app crashes or the app image is not sent. Just the user image along with the name is displayed.

Also, when the text message is sent, the user image is not displayed.

**Comment by kroikie** [comment]
Hi @salimshivani I'm unable to reproduce this, is this still an issue?

**Comment by salimshivani** [comment]
Thank you for the response, but then can internet connectivity be the reason for crashing the app?

Since, in initial stage, the app was just not displaying the imageview for the image sent, but later on, it started crashing.

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#7
