### ISSUE TITLE
Typo: 11. Database Security Rules [Optional]

### ISSUE THREAD

**Issue by loganpowell** [firebase/friendlychat-web#175]
Set Database Security Rules
The Firebase Realtime Database uses a specific rules language to define access rights, security and data validations.

New Firebase Projects are set up with default rules that only allow authenticated users to use the Realtime Database. You can view and **modifies** these rules in the Database section of Firebase console under the RULES tab. You should be seeing the default rules:

**Comment by kroikie** [comment]
Thanks @loganpowell

**Comment by drewswaycool** [comment]
FYI, this typo still exists.

**Comment by nicolasgarnier** [comment]
Thanks @drewswaycool ! Just fixed and re-published.
