### ISSUE TITLE
Section 8: Improper call of FriendlyMessage.class 

### ISSUE THREAD

**Issue by siowze** [firebase/friendlychat-web#186]
I face the problem that salimshivani had pointed out.
In putImageInStorage() , task.getResult().getMetadata() show an error "This method should only be accessed from tests or within private scope."

**Comment by marianobilli** [comment]
Suscribed to wait for the solution, thanks kroikie!

**Comment by lzs15** [comment]
Having this same issue. I believe it is preventing me from adding images.  It updates in the database, but crashes the app every time.

**Comment by digitalblue** [comment]
I modified my code based on this thread https://stackoverflow.com/questions/41105586/android-firebase-tasksnapshot-method-should-only-be-accessed-within-privat

Changed the following for the putImageInStorage method. Hope that helps.
```
if (task.isSuccessful()) {
                            @SuppressWarnings("VisibleForTests") Uri downloadUrl = task.getResult().getMetadata().getDownloadUrl();
                            FriendlyMessage friendlyMessage = new FriendlyMessage(null,
                                    mUsername,
                                    mPhotoUrl,
                                    downloadUrl.toString());
                            mFirebaseDatabaseReference.child(MESSAGES_CHILD).child(key)
                                    .setValue(friendlyMessage);
                        } else { ... }
```

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#6
