### ISSUE TITLE
Can we have friendlychat using Typescript instead of JS ? 

### ISSUE THREAD

**Issue by VaibhavP17** [firebase/friendlychat-web#191]
As we are using typescript more and more nowadays, I think it would be a great idea to rewrite the whole application in Typescript or using the ES6 features.

**Comment by TheBolmanator** [comment]
My observation is exactly the same as @ViabhavP17.

**Comment by VaibhavP17** [comment]
@nicolasgarnier I would also like to contribute to it. Guide me how to do that :)

**Comment by TheBolmanator** [comment]
Fresh today was a comment #213 opened 14 minutes ago by @MatteoNY requesting some "Updates" to the Codelab.  This would go farther than simply making a TS version of this code, and produce the same code via Angular.  I recommend we roll this issue into 213, provided this is accepted (one would hope that the fact that these are all Google technologies we should be inline with the intent of this effort).  I would be very happy to contribute to this as well.

**Comment by kroikie** [comment]
Closing this since we have typescript in the Angular version.
