### ISSUE TITLE
I can't get token

### ISSUE THREAD

**Issue by MiloslavKrejza** [firebase/friendlychat-web#208]
hello i can't get token from a database 

> "Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script. (messaging/failed-serviceworker-registration)."

What can i do to fix this?

**Comment by anevaude** [comment]
I am also having this issue. This comes up on Step 9 of the tutorial, right after you ask the user to accept notifications.

https://codelabs.developers.google.com/codelabs/firebase-web/#9

**Comment by surazzarus** [comment]
I am having the same problem. Could anyone find the solution for this? Thanks

**Comment by Krupen** [comment]
After spending lot of time, I found a solution. This is something that they din't put up in the documentation.

You need to add `firebase-messaging-sw.js` named file with following content to your root (/public) directory 
`    

    importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase-app.js');
    importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase-messaging.js');
    importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase.js');


    var config = {
        apiKey: "<APIKEY>",
        authDomain: "<PROJECTID>.firebaseapp.com",
        databaseURL: "https://<DATABASE NAME>.firebaseio.com",
        projectId: "<PROJECT ID>",
        storageBucket: "<PROJECT ID>.appspot.com",
        messagingSenderId: "<SENDER ID>"
    };
    firebase.initializeApp(config);
    const messaging = firebase.messaging();

    messaging.setBackgroundMessageHandler(function(payload) {
        console.log('[firebase-messaging-sw.js] Received background message ', payload);
        // Customize notification here
        const notificationTitle = 'Background Message Title';
        const notificationOptions = {
            body: 'Background Message body.',
            icon: '/firebase-logo.png'
        };

    return self.registration.showNotification(notificationTitle,
        notificationOptions);
    });
`

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#4

**Comment by jenvigo** [comment]
> After spending lot of time, I found a solution. This is something that they din't put up in the documentation.
> 
> You need to add `firebase-messaging-sw.js` named file with following content to your root (/public) directory `
> 
> ```
> importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase-app.js');
> importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase-messaging.js');
> importScripts('https://www.gstatic.com/firebasejs/4.1.1/firebase.js');
> 
> 
> var config = {
>     apiKey: "<APIKEY>",
>     authDomain: "<PROJECTID>.firebaseapp.com",
>     databaseURL: "https://<DATABASE NAME>.firebaseio.com",
>     projectId: "<PROJECT ID>",
>     storageBucket: "<PROJECT ID>.appspot.com",
>     messagingSenderId: "<SENDER ID>"
> };
> firebase.initializeApp(config);
> const messaging = firebase.messaging();
> 
> messaging.setBackgroundMessageHandler(function(payload) {
>     console.log('[firebase-messaging-sw.js] Received background message ', payload);
>     // Customize notification here
>     const notificationTitle = 'Background Message Title';
>     const notificationOptions = {
>         body: 'Background Message body.',
>         icon: '/firebase-logo.png'
>     };
> 
> return self.registration.showNotification(notificationTitle,
>     notificationOptions);
> });
> ```
> 
> `

This is not working for me... Actually, the file is being generated after building the project.
