### ISSUE TITLE
Codelab out of date  

### ISSUE THREAD

**Issue by MatteoNY** [firebase/friendlychat-web#213]
This is a cool project and I'd like it to work. 
I've been using Firebase on other mini projects with success but simple compared with this Codelab so it would be great to have a working example using advanced features. 
I followed the Codelab and when I got up to the ng build --prod --aot it could not find "AuthProviders, AuthMethods"
I did a Google search and other developers mentioned removing node_modules and using npm again and other tweaks. The GitHub angular/angularfire2 has instructions appear to use AngularFireAuthModule and AngularFireDatabaseModule. I'm going to give them a spin in a new Angular 4 project and see if all works. Just wanted to report that the Codelab did not work on the first try. Thanks, Matt

**Comment by TheBolmanator** [comment]
Would you consider starting a fork for this to share where you are at so far?

**Comment by MatteoNY** [comment]
I'd like to but next week on Monday.

Sent from my iPhone 6

On May 19, 2017, at 5:11 PM, Steve Bolman <notifications@github.com<mailto:notifications@github.com>> wrote:


Would you consider starting a fork for this to share where you are at so far?

**Comment by TheBolmanator** [comment]
In case anyone else finds this post with the same question as I did, (please see) `https://github.com/firebase/friendlychat/tree/master/cloud-functions-angular-start`  this was what I was after.

**Comment by nicolasgarnier** [comment]
@jmdobry Could you have a look?

**Comment by jmdobry** [comment]
@nicolasgarnier I had a look, following the tutorial with a fresh clone of the friendlychat-web repository. I was unable to reproduce the error.
