### ISSUE TITLE
Use of Undefined variable: Uncaught TypeError

### ISSUE THREAD

**Issue by nacojohn** [firebase/friendlychat-web#214]
Under Implementing Message Sending, this error is returned: "Uncaught TypeError: Cannot read property 'push' of undefined at FriendlyChat.saveMessage"

The issue is the use of: **this.messagesRef.push** INSTEAD OF **this.messageRef.push**

Best regard

**Comment by nicolasgarnier** [comment]
It looks to me that `this.messagesRef` is used throughout (in the code and in the codelab instructions). Maybe we fixed it since you filed this bug but if you still see these please re-open and point me to where these issues are.
