### ISSUE TITLE
Firebase-web Codelab down with 403 error

### ISSUE THREAD

**Issue by neilor** [firebase/friendlychat-web#216]
When reading the [Cloud Functions Codelab](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions) I've found an broken service that documentation means as [Firebase Web Codelab](https://codelabs.developers.google.com/codelabs/firebase-web). Can be found in The 0 Step at the first green box of tip. 

https://codelabs.developers.google.com/codelabs/firebase-web

When try to access, I've received an 403 Forbidden error.

Can you help me with this?

**Comment by kroikie** [comment]
Hi @neilor are you unable to clone the repository? What exactly is giving you the 403 error?

**Comment by neilor** [comment]
Hi, I think that should be an little moment that firebase-web codelabs goes down. Because I've tested access firebase-cloud-functions codelabs at the same time and works fine.

Now is working fine! I hope that can close this issue.

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#3
