### ISSUE TITLE
ES6 Version

### ISSUE THREAD

**Issue by jalasem** [firebase/friendlychat-web#219]
I will like to see what the firebase web codelabs looks like in es6. I am sure the community including me will love to learn from it

**Comment by TheBolmanator** [comment]
Please see the  [StackOverflow post](https://stackoverflow.com/questions/44311042/am-i-the-only-person-struggling-with-how-prototype-is-used-in-the-firebase-codel) and provide comments, I would support of this effort if we can find a way around the roadblocks that stopped me.

Specifically sharing AUTH data with the code running outside the prototype.  Of if someone could simply share why the entire app is rolled into the prototype, is this a JS pattern?  Is it required or enforced by Firebase in some fashion, if not why in a tutorial is this pattern applied?  Am I missing something?

**Comment by nicolasgarnier** [comment]
We chose ES5 for backward compatibility as the Firebase SDK supports older browsers that do not support ES6 natively too (And we wanted to avoid having to transpile the code back to ES5).


@TheBolmanator > The tutorial uses pretty common (IMO) pattern to do Object Oriented Programming in ES5.

Just FYI the following code that we use in ES5:

```js
function FriendlyChat() {
  // ...
}

// Sets up shortcuts to Firebase features and initiate firebase auth.
FriendlyChat.prototype.initFirebase = function() {
  // ...
};

// Loads chat messages history and listens for upcoming ones.
FriendlyChat.prototype.loadMessages = function() {
  // ...
};

// Saves a new message on the Firebase DB.
FriendlyChat.prototype.saveMessage = function(e) {
  // ...
}

window.friendlyChat = new FriendlyChat();
```

Would translate to the following, more modern, ES2015 code:

```js
class FriendlyChat {
  constructor() {
    // ...
  }

  // Sets up shortcuts to Firebase features and initiate firebase auth.
  initFirebase() {
    // ...
  }

  // Loads chat messages history and listens for upcoming ones.
  loadMessages() {
    // ...
  }

  // Saves a new message on the Firebase DB.
  saveMessage(e) {
    // ...
  }
}

window.friendlyChat = new FriendlyChat();
```
