### ISSUE TITLE
CODE LABS REQUEST: Polymer 2.0 Friendly Chat (w/ polymerfire elements)

### ISSUE THREAD

**Issue by oneezy** [firebase/friendlychat-web#223]
I'd love to see this codelabs recreated with the Polymer 2.0 `<polymerfire>` elements.

Pretttty pleasssssse ;)

---

https://www.webcomponents.org/element/firebase/polymerfire

**Comment by kroikie** [comment]
Using polymer 2 is not currently on the roadmap, a PR would be welcome if you are keen.
