### ISSUE TITLE
Firebase Web Codelab 

### ISSUE THREAD

**Issue by atlurikamal** [firebase/friendlychat-web#224]
I was going through the Firebase Web Codelab tutorial. At the 6th topic I should be able to see the Sign-In option in the app, But I couldn't. 
Browser: Chrome 
Browser version: 58.0.3029 
I'm using a windows Laptop.  
Here is the link to the topic at which I was getting error (https://codelabs.developers.google.com/codelabs/firebase-web/#5)

**Comment by mvallepintor** [comment]
I'm stuck at the same point. 
Looks like .js is not activated, not called. Even when it's in my code...
@firebase-ops Could you please help us? Thanks in advance!

**Comment by words2708** [comment]
I saw this as well...however I changed the index.html lines 64 through 69 to have buttons unhidden i.e.:
...

64:<button id="sign-out" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
65:Sign-out
66:</button>
67:<button id="sign-in" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
68:<i class="material-icons">account_circle</i>Sign-in with Google
69: </button>
...

**Comment by words2708** [comment]
Thanks for the tutorial. went on smoothly except for this change on my end. if you could update the step 5 user sign in to change index.html or upload an updated index.html that be great.

**Comment by nicolasgarnier** [comment]
Normally you shouldn't have to remove the `hidden` fro the button manually. There is a piece of code which does this automatically depending on the Firebase auth state. See:

[web-start/scripts/main.js - Lines 150-151](https://github.com/firebase/friendlychat-web/blob/master/web-start/scripts/main.js#L150-L151)

```js
FriendlyChat.prototype.onAuthStateChanged = function(user) {
  if (user) { // User is signed in!

    // ...

  } else { // User is signed out!

    // ...

    // Show sign-in button.
    this.signInButton.removeAttribute('hidden');  // <= HERE !!
  }
};
```

Please have a look at your JS console to see if there is an error instead.
If you are experiencing this issue and don't know how to fix it please deploy your code - using `firebase deploy` - and give me the URL here and I'll have a look. Also please let us know which browser you are using just in case.
