### ISSUE TITLE
Sign in problem in android device On step 6

### ISSUE THREAD

**Issue by sohitvermamca** [firebase/friendlychat-web#226]
Google sign-in failed in SignInActivity.java onActivityResult method when the GoogleSignInResult getting back it is not successful. Please solve this issue.

**Comment by arfirman1402** [comment]
I still have same problem here. Whatever I running from android project or android-start project still have same problem. Please help us. Thank you Firebase.

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#2
