### ISSUE TITLE
how can i update firebase-messaging???

### ISSUE THREAD

**Issue by nelsonwilliam11** [firebase/friendlychat-web#229]
my current version is 10.0.1 want to update it to 10.2.+ i couldn't find any way to update it

**Comment by nicolasgarnier** [comment]
Hey!

We've split up this repo in three. One for each platform. If your issue is still valid please reopen in the appropriate repo which are:

 - https://github.com/firebase/friendlychat-web
 - https://github.com/firebase/friendlychat-android
 - https://github.com/firebase/friendlychat-ios
