### ISSUE TITLE
Steps 6,7,8 > Best Practices > Add `functions` to firebase.json

### ISSUE THREAD

**Issue by oodavid** [firebase/friendlychat-web#234]
These steps infer that the functions must be managed independently of the root directory (by way of `cd functions`). As a new user I may not realise that I can deploy these functions in the parent directory, nor that the name of the `functions/` directory is reserved / special.

A better approach may be:

1. Explain the relationship of the `functions/` directory (sample text below)
1. Explain that running `firebase` CLI actually operates within the parent directory (link to an external article explaining how it works up to the nearest directory with a `firebase.json` file etc.)
1. Prompt the user to install `npm` dependences within the `functions/` directory
1. ... carry on as usual

---

`firebase.json` has many default values.

One of which is the `functions` attribute, that points to our `functions/` directory.

You may find it useful to add the default value to `firebase.json` for future reference:

In your `firebase.json` file add a `functions` attribute pointing to our `functions/` directory

### firebase.json

```
{
  ...
  "functions": {
    "source": "functions"
  },
  ...
}

```

**Comment by kroikie** [comment]
I believe we are covering the concerns of this issue.
