### ISSUE TITLE
Step 9 > vision.detectSafeSearch is not a function (solution)

### ISSUE THREAD

**Issue by oodavid** [firebase/friendlychat-web#235]
### Issue

In my **Firebase > Functions > Logs** I see `TypeError: vision.detectSafeSearch is not a function` when executing `blurOffensiveImages`

### Cause

The `vision` npm package installed at the time of writing is newer, and must have a different interface. My installed version is `0.12.0`

### Solution (hack)

Downgrade the vision package to match the example final project, ie: `0.7.1`

### Solution (preferred)

Update the project to use the new vision interfaces

**Comment by nicolasgarnier** [comment]
Thanks for the heads up @oodavid 
Fixed in ec1c77a

**Comment by PatNeedham** [comment]
@nicolasgarnier can you also update the [Content Moderation article](https://firebase.googleblog.com/2017/06/content-moderation-with-cloud-functions.html) to reflect the cloud vision SDK upgrade?
