### ISSUE TITLE
Firebase CLI 3.9.1 firebase use --add not working

### ISSUE THREAD

**Issue by nebrelbug** [firebase/friendlychat-web#237]
In the Firebase FriendlyChat Demo, the below error occurs:

C:\Users\nebre\friendlychat-web\web-start>firebase use --add
? Which project do you want to add? project
? What alias do you want to use for this project? (e.g. staging) messaging

Created alias messaging for project.
Now using alias messaging (project)

However, it doesn't modify the index.html file at all. I'm not sure if I'm doing something wrong, or if it'sa bug.

**Comment by nicolasgarnier** [comment]
this is only meant to connect the CLI and the code to a Firebase project which you have created on the Firebase app console. This way the CLI knows where to deploy your code, which Firebase Database to use etc...  This won't modify the index.html

Is there a specific reason why you thought this would modify the index.html? (I'm just asking in case I can make the codelab instructions more clear :)

**Comment by nebrelbug** [comment]
Thanks for the clarification! In chapter 6, it says: "The Firebase SDK should be ready to use since you have imported and initialized it in the index.html file." When I opened up the test, it displayed an alert saying that I had not initialized the SDK. I think I actually hadn't re-served it, but I assumed that the initialization script should show up. Thanks so much again!

**Comment by nicolasgarnier** [comment]
Indeed I'll change the wording here,. In the past you'd have to modify the `index.html` by hand and we forgot to update this. Nowadays the firebase CLI/hosting serves a special file at the URL `/__/firebase/init.js` which is automatically updated with your project configuration.

Thanks for the help and sorry about that!

Thanks for helping out!

**Comment by erfe1** [comment]
في الواقع سوف تغيير الصياغة هنا،. في الماضي كان لديك لتعديل index.htmlباليد ونسينا لتحديث هذا. في الوقت الحاضر فيليبيس كلي / استضافة يخدم ملف خاص في ورل /__/firebase/init.jsالذي يتم تحديثه تلقائيا مع تكوين المشروع الخاص بك.

شكرا للمساعدة و نعتذر عن ذلك!
