### ISSUE TITLE
Getting an error: can't resolve '@angular/cdk' in ... 

### ISSUE THREAD

**Issue by idofl** [firebase/friendlychat-web#238]
In step 6, running "ng build" fails with the above mentioned error. 

Managed to resolve this by running:
npm install --save @angular/cdk

(or alternatively, update package.json)

**Comment by idofl** [comment]
This is a breaking change in @angular/material 2.0.0 beta 8 (code last updated to 2.0.0 beta 2)

**Comment by gabrielsr** [comment]
#249  fix this issue
