### ISSUE TITLE
Vision API call with wrong function name

### ISSUE THREAD

**Issue by getzdan** [firebase/friendlychat-web#240]
In Step 9, the code includes a call to the Vision API, in the code it is `vision.detectSafeSearch`.
The correct function name is `vision.safeSearchDetection`.
This call appears in the code once in the `cloud-functions-angular` directory, but it also appears in the instructions.

A simple rename fixes the issue.

**Comment by nicolasgarnier** [comment]
Fixed in https://github.com/firebase/friendlychat-web/commit/ec1c77aa59c6125ec0375137c5fc024c7c028059! thanks for the report @getzdan !
