### ISSUE TITLE
Login popup is not working just open and disappear [user sign in step 6]

### ISSUE THREAD

**Issue by fahakhan** [firebase/friendlychat-web#244]
i have done all the 5 step and that is work fine but when i implement  User Sign in 
Failed to load  www.googleapi.com/..../..../       resource: the server responded with a status of 403 ()

![error](https://user-images.githubusercontent.com/17279304/30779828-f13a3348-a114-11e7-8050-72ddd94125a3.PNG)

**Comment by kalvinfromcode** [comment]
I believe signInWithPopup no longer works. I replaced signInWithPopup with signInWithRedirect and it worked. Even the Firebase docs replaced signInWithPopup with signInWithRedirect

**Comment by nicolasgarnier** [comment]
Both should work fine. Looks like you were facing some usage limits. Either your IP has been throttled for using the Firebase auth sign-in too much.

Or there is something wrong with your project (something might not have been initialized correctly) in this case I would try to re-create a project.
