### ISSUE TITLE
Unable to get token.

### ISSUE THREAD

**Issue by gauntface** [firebase/friendlychat-web#245]
Please see: https://github.com/firebase/quickstart-js/issues/150#issuecomment-331041733

**Comment by nicolasgarnier** [comment]
@reyou You are supposed to be creating this file. See the codelabs instructions:

> Create a file named **firebase-messaging-sw.js** at the root of your project with the following content: ...

Have you created the file?

**Comment by reyou** [comment]
@nicolasgarnier you are totally right, once I copied firebase-messaging-sw.js from example docs into my working directory root, it worked. It was my mistake, sorry for wrong alarm.

**Comment by nicolasgarnier** [comment]
No worries! I'm glad you got this sorted :)
