### ISSUE TITLE
In Step 5 - posting of images doesn't work

### ISSUE THREAD

**Issue by mpoehler** [firebase/friendlychat-web#250]
When you create a new project as suggested in step3, the storage is not enabled and the codelab doesn't tell you to do so. If the storage is not enabled, the line "Sign-in to the app by using the SIGN-IN WITH GOOGLE button and feel free to add some messages **and post images**" will not work. 

There is a hint missing in step 3 that you need to enable storage.

**Comment by nicolasgarnier** [comment]
YEs thanks! (looks like the initialization flow for storage changed). I've added a step to enable Cloud Storage on the project (by visiting the **Storage** section).
