### ISSUE TITLE
[STEP-6] Google Identity Toolkit API has not been used in project

### ISSUE THREAD

**Issue by Ashan-FCC** [firebase/friendlychat-web#252]
When I click sign in, It throws an error and is returned to the same page. 
Console has an error message saying to activate the Identity Toolkit API at

**Comment by Ashan-FCC** [comment]
You can activate the Identity Toolkit API from this link. replace <project-id> with your project id. It is something like friendlychat-1234d
https://console.developers.google.com/apis/library/identitytoolkit.googleapis.com/?project=<project-id>

**Comment by nicolasgarnier** [comment]
Thanks @Ashan-FCC,

Strange, the Google Identity Toolkit API should have been automatically enabled on your project. If you see this error feel free to create a new Firebase project, or enable manually as you've done :)

**Comment by pdmshrestha** [comment]
Hi, I get this error only on local emulator. But if I initialize the `firebase-admin`  with `serviceAccount.json`. I don't get this error.

```
const serviceAccount = require("./serviceAccount.json");
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});
```
This works on both emulator and on firebase server

```
admin.initializeApp(functions.config().firebase);    
//admin.initializeApp();
```
This won't work on emulator but works on firebase server. I tried both way.

If anyone has the solution please let me know.
