### ISSUE TITLE
unable to find firebase.js unable to find pi

### ISSUE THREAD

**Issue by madrigal1** [firebase/friendlychat-web#255]
![capture](https://user-images.githubusercontent.com/30615210/33218726-77046500-d164-11e7-8403-14cdc06774fb.JPG)
I have  repeatedly done this part of the tutorial and have followed the instructions to boot The above appears to be an error from your side

**Comment by madrigal1** [comment]
#244 appears to fix the pi error.
yet the following error remains
![capture](https://user-images.githubusercontent.com/30615210/33218922-83a22792-d165-11e7-9a6d-56a92a5e0290.JPG)

**Comment by nicolasgarnier** [comment]
It looks like you are opening the File directly using the browser in the local file path. Instead you need to run `firebase serve`,  this starts a web server and you can access your project using http://loclahost:5000/

**Comment by madrigal1** [comment]
Ah i see :-( my bad 
Thanks for your quick reply
