### ISSUE TITLE
How to send an HTTP request "curl: (6) Could not resolve host" on Windows

### ISSUE THREAD

**Issue by KingOfThePirates** [firebase/friendlychat-web#260]
The [Firebase Web Codelab](https://codelabs.developers.google.com/codelabs/firebase-web/) was essential for me to learn how to use Firebase. I wouldn't be able to do something simple like hosting JavaScript libraries in Firebase without it.

I'm spending the time to write this in hopes it helps someone down the line. I hope this is the appropriate place for this post.

### Problem

I ran into this issue when trying to get curl to send an HTTP request during [step 10. Show Notifications](https://codelabs.developers.google.com/codelabs/firebase-web/#9).

After [installing curl on Windows (in the end, my attempt with this link's method doesn't work)](https://stackoverflow.com/a/28757477/8852317) and testing that curl is installed (input: `curl` output: `curl: try 'curl --help' or 'curl --manual' for more information`), curl in cmd.exe won't properly execute the tutorial's curl command. You get lots of garbage out, but I think a good error to use as a reference for this is `curl: (6) Could not resolve host`.

Here's a reference to the command before replacing the key and token, found at the bottom of https://codelabs.developers.google.com/codelabs/firebase-web/#9:

```bash
curl -H "Content-Type: application/json" \
     -H "Authorization: key=YOUR_SERVER_KEY" \
     -d '{
           "notification": {
             "title": "New chat message!",
             "body": "There is a new message in FriendlyChat",
             "icon": "/images/profile_placeholder.png",
             "click_action": "http://localhost:5000"
           },
           "to": "YOUR_DEVICE_TOKEN"
         }' \
     https://fcm.googleapis.com/fcm/send
```

After replacing the key and token, it doesn't matter if:

- the command is run as-is
- the Linux bash style continue-command-to-next-lines (`\`) are replaced with the Windows's style (`^`)
- the Linux bash style continue-command-to-next-lines (`\`) are removed and all lines are joined
- throwing shots (various curl -options) in the dark and hoping for a lucky hack
- adding `"http://localhost:5000"` to the front
- moving `"https://fcm.googleapis.com/fcm/send"` to the front
- replacing the double quotes (`"`) inside the data option string with double double quotes (`""`) then replacing the start and end single quotes (`'`) with double quotes (`"`)

### Solution

I got it to work by following http://www.oracle.com/webfolder/technetwork/tutorials/obe/cloud/objectstorage/installing_cURL/installing_cURL_on_Cygwin_on_Windows.html#section1 ([[download instructions] Installing cURL on Cygwin on Windows.pdf](https://github.com/firebase/friendlychat-web/files/1587799/Installing.cURL.on.Cygwin.on.Windows.pdf)). As long as you use cygwin.bat, then you can follow the Firebase Web Codelab instructions as-is.

I'm not sure if libcurl in additional to curl was the missing piece or Cygwin or both, but having both works.

This might be a potential problem for Firebase users outside of the friendlychat-web Codelab as well: https://www.youtube.com/watch?v=AAZyQ4Ymkpc&lc=Ugh2f4aY_nz8tHgCoAEC (this linked comment has a reply with a potential solution to try, but at least in my case it wasn't the answer, nor did going down other rabbit holes related to the advice do it for me)

I'm not sure if I overlooked any documentation during my attempt to learn web development that I surely should've run into before becoming aware of Firebase. But depending on if this is a one-off case, it may be a good idea to have documentation or links to known working documentation on any non-Firebase skills similar to sending HTTP requests with curl that are required for learning and using Firebase.

For my purposes, I don't need to keep this issue open. You can close it if you like or keep it open if you feel it appropriate.

**Comment by VictorRed** [comment]
I solve this problem by installing [PostMan](https://www.getpostman.com/) and followind the example of the HTTP request shown in the "Show Notificaction" example

**Comment by nicolasgarnier** [comment]
FYI I just stomped upon this website: https://onlinecurl.com/

It's a hosted version of curl and you can simply paste the cURL command. Pretty cool. I'll be adding a link to that from the codelab for windows users (or in general if cURL is hard to install on your machine). With the caveat that it's unsecure to share your server key with a thrid party service but for tests/ development it's OK :)

**Comment by dilip-k-m** [comment]
Remove space after colon in header.
curl -H "Content-Type:application/json" \
     -H "Authorization:key=YOUR_SERVER_KEY" \
     -d '{
           "notification": {
             "title": "New chat message!",
             "body": "There is a new message in FriendlyChat",
             "icon": "/images/profile_placeholder.png",
             "click_action": "http://localhost:5000"
           },
           "to": "YOUR_DEVICE_TOKEN"
         }' \
     https://fcm.googleapis.com/fcm/send

**Comment by plafferty64830** [comment]
Thanks @KingOfThePirates, I followed the instructions on http://www.oracle.com/webfolder/technetwork/tutorials/obe/cloud/objectstorage/installing_cURL/installing_cURL_on_Cygwin_on_Windows.html#section1 and my cUrl request worked perfectly. 
10/10 from me
