### ISSUE TITLE
Sign-in Issue in Step5

### ISSUE THREAD

**Issue by BhanuPrakashCh** [firebase/friendlychat-web#262]
At Step 5, I was facing the issue with User Sign-in, where after clicking on Sign-in button and selecting the Google Account, it was neither redirecting nor authenticating. Can you please help me on this?

**Comment by Janelgr5** [comment]
I am having the same issue and posted the question on their slack channel. If I get a response I'll post it here.

**Comment by C-Pro** [comment]
Same thing here. After clicking on SIGN-IN WITH GOOGLE, I get the following error response:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "ipRefererBlocked",
    "message": "The referrer https://regal-sun-144102.firebaseapp.com/ does not match the referrer restrictions configured on your API key. Please use the API Console to update your key restrictions.",
    "extendedHelp": "https://console.developers.google.com/apis/credentials?project=88478223524"
   }
  ],
  "code": 403,
  "message": "The referrer https://regal-sun-144102.firebaseapp.com/ does not match the referrer restrictions configured on your API key. Please use the API Console to update your key restrictions."
 }
}
```
In firebase console I have enabled Google Auth provider and there is regal-sun-144102.firebaseapp.com 
domain listed below in the authorized domains list.

**Comment by nicolasgarnier** [comment]
Normally the API referrer restriction is automatically configured at project creation time.

I'm guessing something wrong happened when your Firebase project was created (I've seen some rare occurrence of that) and not everything was initialized correctly. 

Could you please try creating a new Firebase project and re-configuring your CLI for it? `firebase use --add`

**Comment by wu4f** [comment]
Two things that I ran into with regard to this lab:

#1 If you're using firebase serve to get a preview of the app, you need to enable the domain it is served from in Firebase=>Authentication=>Sign-in Method=>Authorized Domains.   By default, the domain when doing firebase deploy is enabled by default

#2 The mechanism requires you to have third-party cookies enabled.  (Mine weren't).  So, in Google Chrome=>Settings=>Advanced=>Privacy and Security=>Content Settings=>Cookies=>Block Third Party Cookies,  set it to disable

**Comment by 700000000** [comment]
Hi Murdy, I do not have a good phone number for you so give me a call...I would love to give you a 10 minute demo when you are in front of a computer.  I usually suggest the Silver or Gold plan.  I attached a link to my  Facebook page.  If you'd like a quick video that sums up what we do, CLICK HERE!
https://www.facebook.com/Sharon-Virag-Realtor-Rodeo-Realty-1222785424475900

We also offer Facebook cover photo's for $49 I attached the photo's you can choose from.

Here's what sets us apart: We guarantee that the content we post on your behalf will be seen by thousands of Facebook users in your target market every single month. No other company in real estate can say that.

Back At You Media also provides:

Listing and Open House tool that immediately improves the look and thus the performance of your posts
A boosting tool where you can choose your own budget
Fully-licensed content posts, including Local Market Charts and blogs
Customizable lead capture pages, including a Home Valuation Tool
Hyper-targeted Facebook ads
Content scheduling tool for simultaneous posting to Facebook, Twitter and LinkedIn
Educational Webinars
World-Class Support
Pricing Information:
One-time Activation Fee:  $49 for annual.  $99 for 6 mo. plan and $149 for monthly.    

Available Packages:
NAR Starter: $120 annually or $15 monthly - Social Media Center (SMC) to publish your listings and a personalized Home Value tool.  Single Property Websites for listings and auto-posting of future listings. Social Media Listing Reports. You get our Great Facebook Boosting Technology.   NAR Activation is $49 

Bronze: $588 annually or $300  6 mo. plan. or $69 monthly- SMC plus management of Facebook, Twitter and Linkedin. Includes content, lead capture landing pages, and auto-publish for your listings.   

Silver: $1,188 annually or $600 6 mo. plan or $119 monthly - SMC plus management of Facebook, Twitter and Linkedin. Includes Content, lead capture landing pages, and publish your listings. PLUS branding for your business. We guarantee you'll reach a minimum of 6k people per month.   

Gold: $3,588 annually or $1800 6 mo. plan or $349 monthly.  - SMC plus management of Facebook, Twitter and Linkedin. Includes Content, lead capture landing pages, and auto-publishing for your listings. PLUS branding for your business. We guarantee you'll reach a minimum of 6k people per month. PLUS +/- 100 leads annually.  

Platinum: $5,988 annually or $599 monthly - SMC plus management of Facebook, Twitter and Linkedin. Includes Content, lead capture landing pages, and auto-publishing for your listings. PLUS branding for your business. We guarantee you'll reach a minimum of 6k people per month. PLUS +/- 150 leads annually. 

Diamond: $11,988 annually or $1199 monthly - SMC plus management of Facebook, Twitter and Linkedin. Includes Content, lead capture landing pages, and auto-publishing for your listings. PLUS branding for your business. We guarantee you'll reach a minimum of 6k people per month. PLUS +/- 300 leads annually.   

*Monthly payment plans available*

Please don't hesitate to reach out with any questions and take a look at the following links for examples of what we do.

SAMPLE FACEBOOK PAGE

FEATURED PROPERTY WEBSITE

PROPERTY REPORT (for Boosted listings)


Thank you!  Lets Talk! Sharon Virag~


	
Sharon Virag
Social Media Expert at Back At You Media
Your Facebook Marketing & Technology Team
O
E
818-990-0565 x 110
sharon.virag@backatyou.com

Proud Partner in NAR's REALTOR Benefits® Program.
