### ISSUE TITLE
'firebase --version' shows version of firebase-tools, not firebase

### ISSUE THREAD

**Issue by djmailhot** [firebase/friendlychat-web#264]
From the [codelab](https://codelabs.developers.google.com/codelabs/firebase-web/#3):  "Make sure `firebase --version` is above 3.3.0"

When I run it:
`$firebase --version`
`3.17.3`

This turns out to be the package version of [firebase-tools](https://www.npmjs.com/package/firebase-tools), not [firebase](https://www.npmjs.com/package/firebase) (as of 2018/01/22)

Perhaps they changed the firebase CLI recently.  Maybe my firebase installation got wacked.  Either way, if you repro, you know what to do.

**Comment by nicolasgarnier** [comment]
Thanks! the wording was not correct. we indeed want to check for the firebase-tools version. I'll update that.
