### ISSUE TITLE
403 Disallowed user agent from iOS device

### ISSUE THREAD

**Issue by AngryDrunkard** [firebase/friendlychat-web#265]
I completed the entire codelab with no issues. Good job on the tutorial, I felt I learned a lot. While attempting to talk to myself from various devices I tried using my iPhone. When I attempted to authenticate from the phone I receive a 403 disallowed user agent error, I receive the same error when using an iPad. I did some searching on the issue but was not able to determine if this is actually a bug or maybe the authentication method in the codelab needs updated? I'm still learning so my apologies.

**Comment by nicolasgarnier** [comment]
I believe this is related to: https://github.com/firebase/firebase-js-sdk/issues/77

Closing in it's favor
