### ISSUE TITLE
This App is broken at the log in

### ISSUE THREAD

**Issue by tomcatbuzz** [firebase/friendlychat-web#266]
I am not sure why this is being maintained here when there is no issues being fixed. This is broken in step 5
and won't show a log in button. Pointless to learn if it don't work. Files are miss matched from Web-start and Web (final).

**Comment by nicolasgarnier** [comment]
Hey @tomcatbuzz, sorry this is not working for you. Normally this codelab should be entirely functional. Can you please give specifics of what's not working for you? I'm sure we can figure it out :)

**Comment by tomcatbuzz** [comment]
I apologize, I performed further troubleshooting. I had originally started this project some time ago. When I returned to  the tutorial it had put me where I left off. So I just backed up to the code editing parts, where most mistakes are made, and I had missed a bracket after the check if signed in function. The previous code TODOs had the bracket already there.
