### ISSUE TITLE
Add additional instruction in section (13. Deploy your app using Firebase static hosting)

### ISSUE THREAD

**Issue by bobbydreamer** [firebase/friendlychat-web#267]
Hi,

You can add additional instruction in section(13. Deploy your app using Firebase static hosting) before issuing cmd(firebase deploy) to stop (firebase serve) if it is running. I encountered an issue when i have firebase server running in one window and i was not able to deploy. I was getting below error message and there was not explanation why it occurred.

i  functions: preparing functions directory for uploading...
i  hosting: preparing ./ directory for upload...

Error: An unexpected error has occurred.

Thanks,
Sushanth

**Comment by nicolasgarnier** [comment]
I double checked this on the latest build and it seems this issue is now gone :)
