### ISSUE TITLE
Error with donwload imagens of storage

### ISSUE THREAD

**Issue by israeleriston** [firebase/friendlychat-web#270]
Hello guys

i'am have problem with donwload imagens of storage the firebase

desclaimer 

my rules 
`service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
`

gist the example
https://gist.github.com/israeleriston/df0706018c5d9a7b6e137ea1e3ab3d06
harded code, example of downlod imagens

path's of imagens into storage firebase and imagens and path existing 
` const img = ['images/education/bauru/elementaryI/carousel02', 'images/education/bauru/elementaryI/carousel01' ]
`

**Comment by nicolasgarnier** [comment]
To help you out we'll need more detail about your issue: What's the error message, what's not working and what were you expecting.

Also, it looks like this is not about friendlyChat which is our Codelab. For general purpose help please post on StackOverflow instead: stackoverflow.com
