### ISSUE TITLE
Cannot read property 'authDomain' of undefined

### ISSUE THREAD

**Issue by pablovilla83** [firebase/friendlychat-web#271]
This happened on Step 10 "New Message Notifications" from the Cloud Functions for Firebase codelab. The error logged from the 'sendNotification' Cloud Function as follows:

sendNotifications | TypeError: Cannot read property 'authDomain' of undefined at exports.sendNotifications.functions.database.ref.onCreate.snapshot (/user_code/index.js:106:58) at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:112:27) at next (native) at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71 at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12) at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:82:36) at /var/tmp/worker/worker.js:700:26 at process._tickDomainCallback (internal/process/next_tick.js:135:7)
-- | --

Doing some digging I found the following:

> The authDomain relies on specific scripts being available on that domain. If your Single-Page App is hosted on Firebase Hosting with a custom domain, you will be able to use that domain as the authDomain.
> Alternatively, you could set up a custom domain for Firebase Hosting on a subdomain of your domain e.g. auth.foobar.com and you'd then be able to use auth.foobar.com as your authDomain.
> There is currently no support for using a non-Firebase-Hosting domain as your authDomain.
https://stackoverflow.com/questions/40856179/custom-authdomain-in-firebase?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Changing the following lines fixed the issue:
// click_action: `https://${functions.config().firebase.authDomain}`,
click_action: `https://${PROJECT_ID}.firebaseapp.com/`,

**Comment by nicolasgarnier** [comment]
Thanks Pablo. Indeed I forgot to change this. `functions.config().firebase` is gone in the latest version of the SDK.
