### ISSUE TITLE
Stalled in Step 7

### ISSUE THREAD

**Issue by Caio-Rezende** [firebase/friendlychat-web#272]
Issue loading the messages, the request loading them never returns, it stalls...

**Comment by Caio-Rezende** [comment]
it happens that reading the friendlychat-android issues I found a similar stalling in Step 7, and it suggests the checking of the rules settings, supposedly in Step 6. In this friendlychat-web codelab, it is not there any reference in Step 6 to rules... changing the settings of the database from private to public solved my issue, allowing me to continue. I'll further read the docs on the rules to make it better than public.

**Comment by Erica42** [comment]
Thank you for the note about changing from private to public. I was having the same issue and this worked for me.
