### ISSUE TITLE
Step 9 Pass in User not Event

### ISSUE THREAD

**Issue by polen-chheang-dmi** [firebase/friendlychat-web#275]
Step 9 index.js

`exports.addWelcomeMessages = functions.auth.user().onCreate((event) => {
  const user = event.data;`

Should be replace with:

`exports.addWelcomeMessages = functions.auth.user().onCreate((user) => {`

Reference https://firebase.google.com/docs/auth/extend-with-functions#trigger_a_function_on_user_creation

**Comment by nicolasgarnier** [comment]
@polen-chheang-dmi could you tell me where you see this? I don't see any issues with https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#7

**Comment by polen-chheang-dmi** [comment]
Hi @nicolasgarnier, Yes, it was updated. I am not sure when the update happen but while i am practicing the codelab, **event** is passed to onCreate instead of User.
I close this issue, Thanks for response. Cheer!
