### ISSUE TITLE
Step 12 seems to be missing parts 3 & 4

### ISSUE THREAD

**Issue by danrye** [firebase/friendlychat-web#276]
3. In the Angular app, change the font and boldness of new messages based on their sentiment.
4. Also in the Angular app, display a list of recently discussed topics as new messages are added.

**Comment by nicolasgarnier** [comment]
@jmdobry ptal

**Comment by jmdobry** [comment]
The functionality to do the steps you mentioned is implemented for you, as the Cloud Functions Angular tutorial focuses on the Cloud Functions. I updated the tutorial to call this out.
