### ISSUE TITLE
Database setup and default rules have changed, requires updates

### ISSUE THREAD

**Issue by CodingDoug** [firebase/friendlychat-web#278]
The codelab doesn't yet address the new setup of the database in the console.  The console now requires you to:

1. First select if you want to use Realtime Database or Firestore.
2. After choosing Realtime Database, which default rules you want to use (either fully open or fully locked).

This impacts not only setup, but also step 11 which claims that the default rules require auth.  This is no longer an option with the new setup.

The fully locked option won't work for the codelab, so the instructions should probably choose fully open *or*, the codelab should have instructions to immediately modify them to require auth.

**Comment by kylejsarte** [comment]
Agreed. For any absolute beginners (such as myself) who are having issues getting the messages to update after completing step **_7. Read messages_**, you will need to make changes to your _Database > Rules_ as CodingDoug mentions above and set your _.read_ and _.write_ properties to _true_.

**Comment by vsoch** [comment]
+1 to this issue! I am a first time user of Firebase and trying to figure out if I want to start in Locked mode (or not). What seems to be the case is that this setting is creating a Database "Rule" that is defined in the Database --> Rules tab. I started in test mode, and then browsed to this tab to change to only allow write for logged in users:

```bash
// Allow read/write access on all documents to any user signed in to the application
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```
I don't think this is ideal still, but it's a "testing" level that is slightly better than "anyone anonymous come and destroy!"  Here are the docs on security rules:

https://firebase.google.com/docs/firestore/security/get-started?authuser=0

As an unrelated aside, the security rule dog... he means business!

![image](https://user-images.githubusercontent.com/814322/40255053-a5da2f80-5a9a-11e8-83de-6e714e8926db.png)

**Comment by nicolasgarnier** [comment]
All this has now been updated, initialization steps have been updated to the new onboarding UI and the rules section has been updated to make it a bit more secure.
