### ISSUE TITLE
Would changing the name of the project effect accessing the database in step 7?

### ISSUE THREAD

**Issue by CJohnDesign** [firebase/friendlychat-web#279]
I changed the name of this from the start because I want to build on top of it for a project I'm working on but I can't get step 7 to work. Everything else looks correct but the messages won't populate.

**Comment by ashishvibhakar** [comment]
I have not changed to name, but still messages not showing in step 7... Stuck in the code labs... Please help!

**Comment by ashishvibhakar** [comment]
I have not changed the database name, but still messages not showing in step 7... Stuck in the code labs... Please help!

**Comment by hungnd11** [comment]
@ashishvibhakar  I encountered the same problem. You can fix it by changing the permission (in the Rules tab of Databases) such that all authenticated users can read from and write to the database:
```
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

The original value of rules is:
```
{
  "rules": {
    ".read": false,
    ".write": false
  }
}
```

**Comment by nicolasgarnier** [comment]
I changed the initialization steps of the codelab to make sure the security rules are set properly now :)
