### ISSUE TITLE
Hosting ignore rules missing the functions

### ISSUE THREAD

**Issue by maxcorbeau** [firebase/friendlychat-web#282]
`firebase.json` is missing the rule to ignore functions for hosting:
https://codelabs.developers.google.com/codelabs/firebase-web/#11

```
  "hosting": {
    "public": "./",
    "ignore": [
      "firebase.json",
      "database-rules.json",
      "storage.rules"
    ]
  }
```

Whereas the actual file has it:
https://github.com/firebase/friendlychat-web/blob/master/web/firebase.json#L5-L7.json

The risk is that people overwrite `firebase.json` with code from the doc and end up pushing functions to cloud storage. It's OK for a test project, but if they take the bad habit and start pushing their source (eg authentication functions), in production that might be problematic.

**Comment by nicolasgarnier** [comment]
Just added it! Thanks for pointing this out @maxcorbeau
