### ISSUE TITLE
Step 6 is broken

### ISSUE THREAD

**Issue by Buravchik** [firebase/friendlychat-web#285]
Platforms: MacOS, Win10.
Browser: Chrome 67.

Problem: Doing step 6. Deployment successful. Cant see messages in chat after sending them. I can see them in DB.

> polyfills.50b851ccd19aa9b94ce1.bundle.js:1
> Uncaught TypeError: Object(...) is not a function
>     at e.project (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e._next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e.next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e._next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e.next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e.next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e._next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e.next (main.89deea38e9ef8891dca3.bundle.js:1)
>     at t.observe (main.89deea38e9ef8891dca3.bundle.js:1)
>     at e.dispatch (main.89deea38e9ef8891dca3.bundle.js:1)

**Comment by nicolasgarnier** [comment]
@jmdobry any ideas?

**Comment by jmdobry** [comment]
@nicolasgarnier @Buravchik I just tried the tutorial again with a fresh clone of the friendlychat-web repository. I have not encountered any errors. It's possible there was a bug in RxJS. The app is not pinned to a specific version, so re-installing deps may work, but I'm assuming you've already tried that.

**Comment by nicolasgarnier** [comment]
@Buravchik let us know if you are still experiencing the issue! I'll close for now
