### ISSUE TITLE
Step 9: Uploading an image

### ISSUE THREAD

**Issue by CatsAreMLG** [firebase/friendlychat-web#291]
I am getting the error

> Uncaught TypeError: Cannot read property '0' of undefined
So I can't see the image that has been uploaded to the server
also
> Unable to get messaging token.
So I can't get the notification token

https://the-bois.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
FYI the codelab has been updated. But for you since you've already started the fix above is easier (than restarting the entire codelab) :)
