### ISSUE TITLE
I am unable to get the notifications to work

### ISSUE THREAD

**Issue by CatsAreMLG** [firebase/friendlychat-web#292]
The console gives this error

Unable to get messaging token. {code: "messaging/failed-serviceworker-registration", message: "Messaging: We are unable to register the default s…t. (messaging/failed-serviceworker-registration).", browserErrorMessage: "Failed to register a ServiceWorker: A bad HTTP res…code (404) was received when fetching the script.", stack: "FirebaseError: Messaging: We are unable to registe…m/__/firebase/5.1.0/firebase-messaging.js:1:34104"}

https://the-bois.firebaseapp.com/

**Comment by nicolasgarnier** [comment]
It seems that you have not created the service workers file `firebase-messaging-sw.js` as instructed in Step 10 of the codelab: https://codelabs.developers.google.com/codelabs/firebase-web/#9
Under the title **Add the Firebase Messaging service worker**

It should work after that :)
