### ISSUE TITLE
Step 8 as-written results in "Unexpected token" error

### ISSUE THREAD

**Issue by dougmakingstuff** [firebase/friendlychat-web#293]
When following the instructions, line 55 has a typo and results in an Unexpected Token error.

Given in page:
```
function loadMessages() {
  // Loads the last 12 messages and listen for new ones.
  var callback(snap) {
    var data = snap.val();
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };

  firebase.database().ref('/messages/').limitToLast(12).on('child_added', callback);
  firebase.database().ref('/messages/').limitToLast(12).on('child_changed', callback);
};
```

Same line in final script:
```
function loadMessages() {
  // Loads the last 12 messages and listen for new ones.
  var callback = function(snap) {
    var data = snap.val();
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };

  firebase.database().ref('/messages/').limitToLast(12).on('child_added', callback);
  firebase.database().ref('/messages/').limitToLast(12).on('child_changed', callback);
};
```

**Comment by paraxc74** [comment]
callback needs to be a function, right?

function loadMessages() {
  // Loads the last 12 messages and listen for new ones.
  **function** callback(snap) {
    var data = snap.val();
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };

  firebase.database().ref('/messages/').limitToLast(12).on('child_added', callback);
  firebase.database().ref('/messages/').limitToLast(12).on('child_changed', callback);
};

**Comment by nicolasgarnier** [comment]
Thanks for the report! There was a bad replace-all. Just fixed  :)

**Comment by j-avila** [comment]
why I can't  show the mmessages imported in the database? my code is exactly the same
// Loads chat messages history and listens for upcoming ones.
function loadMessages() {
  // Loads the last 12 messages and listen for new ones.
  function callback(snap) {
    var data = snap.val();
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };
  
    firebase.database().ref('/messages/').limitToLast(12).on('child_added', callback);
    firebase.database().ref('/messages/').limitToLast(12).on('child_changed', callback);
  };
