### ISSUE TITLE
Tool Tip Bug

### ISSUE THREAD

**Issue by jaysonfrazer** [firebase/friendlychat-web#300]
Hi guys, in the Firebase codelab for friendly chat, there is a mouse tooltip that fires on every part of the page, so every time you move the mouse, the tool tip pops up no matter where you are on the page, it's really annoying and not the right use of a tool tip IMHO. Is this a mistake?
 The page I'm on is ...

https://codelabs.developers.google.com/codelabs/firebase-web/#7

**Comment by nicolasgarnier** [comment]
This issue was moved to googlecodelabs/tools#97
