### ISSUE TITLE
Web-start step 8 (Read messages): loadMessages function does not appear to do anything

### ISSUE THREAD

**Issue by bbbbencody** [firebase/friendlychat-web#302]
SOLVED: I had to update my rules in my Realtime Database. I had 'read: false'. Leaving my issue report as record of my stupidity. Maintainers may delete it if it's unhelpful.

ORIGINAL ISSUE:
I have followed the instructions and copy-pasted the code exactly from the tutorial. The sample messages are correctly loaded into my Realtime Database and I am able to read them from the firebase CLI. When I call loadMessages from the chrome console, it is defined, and its definition matches the one in the tutorial, but nothing happens. I think something is outdated in either the description or the code snippet itself, since the description mentions "the callback function -- setMessage" and there is nothing called setMessage anywhere in the code. From what I can tell from inserting log statements, the callback function is never called. And I can't call it myself manually to see what happens, because I don't know what "snap" is supposed to be.

EDIT: I was able to define the callback function as a standalone function in-console and build a 'snap' parameter that looked like the following:

`snap = {key:'asdfjkl', val: function() { return {name:'garbage', text:'bwah', profilePicUrl: '', imageUrl:''}}}`

This successfully loaded the message in my chat window. Still no clue how to trigger the actual callback, since the code provided doesn't do it, and the code provided is supposed to teach me how to do it.

Also, since there's nowhere to leave feeback on the tutorial itself, I'm going to leave some here. This is a badly written tutorial. I already know how to copy and paste blocks of code. This tutorial does almost zero explaining of what the sample code actually does. For example, the loadMessages function provided:

```function loadMessages() {
  // Loads the last 12 messages and listen for new ones.
  var callback = function(snap) {
    var data = snap.val();
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };

  console.log("callback defined, what happened?");
  firebase.database().ref('/messages/').limitToLast(12).on('child_added', callback);
  firebase.database().ref('/messages/').limitToLast(12).on('child_changed', callback);
}
```

I know that this function is necessary to get my messages from my firebase realtime database. But I'm not able to extend this knowledge to a real life use case because I have no clue what this code does.

- Where does the 'snap' parameter come from in the callback function? what do we expect it to look like?
- We have a ton of functions chained on to firebase.database(). what does 'ref' do? I assume it's the path under which I'd like to retrieve data? by the time I get to 'on', what am I calling 'on', on? I don't know what limitToLast(12) actually returns. What are the triggers I can listen to with 'on'? what does 'child_added' or 'child_changed' do?
-what does displayMessage do? It's defined lower down in the code, but I'm not sure what it does in the context of this app, as I'm new to firebase.

**Comment by gosieg** [comment]
I ran into the same issue. Changing the read (and write) flag to true fixed it for me too. I think the issue has something to do with the new Firestore database showing up by default now.

**Comment by nicolasgarnier** [comment]
Hey @gosieg and @bbbbencody 

There is a section in Step 3 of the codelab that runs you through the UI to chose the correct security rules:

![image](https://user-images.githubusercontent.com/3766663/44176766-6a8a3000-a0eb-11e8-9afb-c829bfef6b05.png)

Just to know if that part can be improved: Did you simply miss it? Or was there a bug during this flow?

I know it's frustrating when something doesn't work and you don't know why ;) FYI in this case checking the JS console should give a clue (there should be some "Permission denied" error)  I should add an Issue template making sure people had a look at the JS console before posting :D

**Comment by nicolasgarnier** [comment]
Just updated the "the callback function - setMessage -" sentence which indeed did not get updated in the last code update and made it a bit more clear that `.ref()` is used to specify the path.

**Comment by robflaherty** [comment]
Same problem/resolution here. It seems to be what @gosieg said: Create Database defaults to Firestore. So when you select test mode in Step3 you're selecting it for Firestore. Then when you switch to Realtime Database the default is locked mode.

**Comment by nicolasgarnier** [comment]
Any way we can improve the text in Step 3 tu make sure developers create a database with the Realtime Database rather than Firestore?

> ...maybe it's time to switch that codelab to use Firestore :D

**Comment by noname2534** [comment]
I​Want connecting​the​device​

**Comment by nicolasgarnier** [comment]
I added a warning where we ask to enable the Realtime Database. Hopefully this makes things better:

![image](https://user-images.githubusercontent.com/3766663/46257312-bb958e00-c4b7-11e8-87a1-96c96c2038f4.png)
