### ISSUE TITLE
Step - 8 i.e Read Messages doesn't work

### ISSUE THREAD

**Issue by vishal758** [firebase/friendlychat-web#321]
I was going through the Firebase Web Codelab tutorial. I did what it said (by importing the initial_messages.json ) and it was done successfully and shown in the database section but when I run the app on localhost it was not showing any output messages(i.e the test messages we set initially to see some output from our app).
Therefore the further steps (i.e see messages that we will type in the send box) can't be done. Can anyone help resolving the issue.

**Comment by yunchurlee** [comment]
I am also not able to complete STEP 8. 
Unfortunately, there is no error message I can find. 
It seems like it does not call call back function

`function loadMessages() {
  // TODO 7: Load and listens for new messages.
  var callback = function(snap){
    var data = snap.val();
    console.log(data);
    displayMessage(snap.key, data.name, data.text, data.profilePicUrl, data.imageUrl);
  };

  firebase.database().ref('/messages/').limitToLast(12).on('child_added',callback);
  firebase.database().ref('/messages/').limitToLast(12).on('child_changed',callback);
}
`
I put console.log(data), but it never product console log at all. 
and no error message on browser console log and terminal side
