### ISSUE TITLE
[Firebase Web Codelab] Step 3 > Enable Google Auth > Outdated image

### ISSUE THREAD

**Issue by YikSanChan** [firebase/friendlychat-web#324]
What's in the codelab:
![image](https://user-images.githubusercontent.com/17229109/46590210-62ed6480-ca66-11e8-8ace-d7842e32dd5f.png)
What's I see:
![image](https://user-images.githubusercontent.com/17229109/46590227-78628e80-ca66-11e8-97aa-520a74db7fb1.png)
There is a field missing in the codelab, i.e, "Project support email".

**Comment by nicolasgarnier** [comment]
Thanks @YikSanChan, just fixed it.
