### ISSUE TITLE
[Firebase Web Codelab] Step 8 > Import Messages > Sentence misplacement

### ISSUE THREAD

**Issue by YikSanChan** [firebase/friendlychat-web#330]
In the overflow menu of the Database select Import JSON. Browse to the initial_messages.json file at the root of the repository, select it then click the Import button. This will replace any data currently in your database.

[image]

You could also edit the database manually, using the green + and red x to add and remove items manually or use the Firebase CLI with this command:

```
firebase database:set / ../initial_messages.json
```
=======================should be=======================

In the overflow menu of the Database select Import JSON. Browse to the initial_messages.json file at the root of the repository, select it then click the Import button.

[image]

Or use the Firebase CLI with this command:

```
firebase database:set / ../initial_messages.json
```

You could also edit the database manually, using the green + and red x to add and remove items..

**Comment by nicolasgarnier** [comment]
fixed
