### ISSUE TITLE
[Firebase Web Codelab] Step 13 > Deploy Storage Security Rules > Redundancy

### ISSUE THREAD

**Issue by YikSanChan** [firebase/friendlychat-web#333]
You can then deploy these rules with the Firebase CLI using `firebase deploy --only storage`:
```
firebase deploy --only storage
```

============================should be============================ 

You can then deploy these rules with the Firebase CLI:
```
firebase deploy --only storage
```

**Comment by nicolasgarnier** [comment]
fixed
