### ISSUE TITLE
[Firebase Web Codelab] Step 14 > why `--except functions`

### ISSUE THREAD

**Issue by YikSanChan** [firebase/friendlychat-web#334]
Why do we need to add `--except functions`? Didn't we add `functions` to `ignore` list?

**Comment by nicolasgarnier** [comment]
@YikSanChan 

```json
"hosting": {
    "public": "./",
    "ignore": [
      // ...
      "functions"
    ]
  }
```

This will only make sure that the `functions` directory is not deployed as public static assets by firebase hosting whereas `firebase deploy --except functions` will make sure we don't publish Cloud Functions that may be inside the  `functions` directory (there are none, but then we would get additional steps in the console log where the Functions API would be enabled etc... ).

I should probably change and move the public files to a `public` subdirectory (it's better practice, there would be no `ignore` statement anymore so it would be simpler).

**Comment by nicolasgarnier** [comment]
Just moved all public files to the "public" subdirectory and updated the instructions.
