### ISSUE TITLE
404 Not Found: @google-cloud/promisify@^0.3.0

### ISSUE THREAD

**Issue by chandragaajula** [firebase/friendlychat-web#339]
I'm attempting to follow the instructions in **Cloud Functions for Firebase (Angular)** and in the section "[10. Images moderation](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions-angular/index.html?index=..%2F..%2Findex#9)"  I've been asked to install dependencies by running the command:

`npm install --save @google-cloud/vision @google-cloud/storage child-process-promise`

However, I get the following error when I run the above command:

> npm ERR! code E404
> npm ERR! 404 Not Found: @google-cloud/promisify@^0.3.0

> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/XXXXXXXX/.npm/_logs/2018-10-20T07_34_34_069Z-debug.log

Snippet from the above logs is stored in https://pastebin.com/FxaRMHQi

**Comment by nicolasgarnier** [comment]
@jmdobry PTAL

**Comment by nicolasgarnier** [comment]
FYI in the non-angular sample we've fixed the installed version of these dependencies to avoid having the codelab broken by non backward-compatible changes of `@google-cloud/vision` and `@google-cloud/storage`

**Comment by kroikie** [comment]
This looks resolved to me.
