### ISSUE TITLE
Small error in the text

### ISSUE THREAD

**Issue by danicat** [firebase/friendlychat-web#346]
In the following text the codelab mentions **three** packages, but actually there are only two. The text after the code snippet is correct and mentions two packages.

![screenshot 2018-11-10 at 8 39 34 pm](https://user-images.githubusercontent.com/5531172/48307353-249a0800-e532-11e8-9e8c-b9a60899f47c.png)

**Comment by danicat** [comment]
"To install these **three** packages..."

**Comment by nicolasgarnier** [comment]
Thanks for the catch! (there used to be three :))

**Comment by nicolasgarnier** [comment]
published!
