### ISSUE TITLE
Step 13 "storage-rules.json" ?

### ISSUE THREAD

**Issue by syon** [firebase/friendlychat-web#347]
Hi. Thanks the nice tutorial.

Here is my confusing point. These are typo?
<img width="1106" alt="_2018-11-11_21_25_53-2" src="https://user-images.githubusercontent.com/3148102/48313309-a9058d00-e5fd-11e8-9359-f1da11f30c3a.png">

---

Related info:

<img width="1107" alt="2018-11-11 21 57 10" src="https://user-images.githubusercontent.com/3148102/48313310-ad31aa80-e5fd-11e8-960e-7aa59a911e5b.png">
<img width="1134" alt="_2018-11-11_21_51_24" src="https://user-images.githubusercontent.com/3148102/48313312-b28ef500-e5fd-11e8-82f7-c91f449b4001.png">

**Comment by nicolasgarnier** [comment]
Goo dcatch thanks! I'm updating the instructions to have "storage.rules" everywhere :)
