### ISSUE TITLE
web codelab code error

### ISSUE THREAD

**Issue by Kpconway519** [firebase/friendlychat-web#348]
https://codelabs.developers.google.com/codelabs/firebase-web/#9

in the code sample, one of the lines reads 'storageUri" instead of "storageUrl'

**Comment by nicolasgarnier** [comment]
@Kpconway519 actually this is correct, this value is the URI of the file in Cloud storage. (for Cloud storage we usually use the term URI and not URL). See: https://cloud.google.com/bigquery/external-data-cloud-storage#gcs-uri
