### ISSUE TITLE
Having a React Tutorial

### ISSUE THREAD

**Issue by EstebanMarin** [firebase/friendlychat-web#350]
Are you going to update the documentation to have a React Tutorial?

**Comment by jhuleatt** [comment]
We've been working on a new version of the ReactFire library (it is currently in alpha).

Here's a live example: https://stackblitz.com/edit/reactfire-sample

And a full quickstart: https://github.com/FirebaseExtended/reactfire/blob/master/docs/quickstart.md#reactfire-quickstart

**Comment by EstebanMarin** [comment]
Cool!! thanks
