### ISSUE TITLE
integrate with asp c#

### ISSUE THREAD

**Issue by weedkiller** [firebase/friendlychat-web#371]
Hi, how do we integrate into asp mvc or core app.

thanks

**Comment by jhuleatt** [comment]
Can you please clarify what you'd like to be able to do with .net?

**Comment by jhuleatt** [comment]
I'm going to close this since the original issue is pretty old. Please comment if you'd like to reopen it.

**Comment by weedkiller** [comment]
Hi we would like to use firebase in our ASP application, and as part of that we were working off this sample (to give you some context)

I would like to use the C# backend and both talk to firebase in the sample, and also would like to know how to perform the tasks in the app in conjunction with C#. I looked at the docs for help but did not find the snippets to achieve the same.
