### ISSUE TITLE
Mistake in the codelab's documentation of firebase.json 

### ISSUE THREAD

**Issue by yagyanshbhatia** [firebase/friendlychat-web#375]
In the hosting attribute in `.firebaserc`, the `"public" = "./"` won't work, it should be changed to `./public`, otherwise, page not found default page comes up after hosting.
here: https://codelabs.developers.google.com/codelabs/firebase-web/#13
(even in the `web` directory, its correct as `./public`)

**Comment by nicolasgarnier** [comment]
Fixed thanks!
