### ISSUE TITLE
Typos in /codelabs/firebase-web Step 4

### ISSUE THREAD

**Issue by FeynmanDNA** [firebase/friendlychat-web#376]
4. Install the Firebase command line interface
The Firebase command line interface (CLI) allows you to **user** Firebase Hosting to serve your web app locally as well as to deploy your web app to your Firebase project.

I think the word **user** should be **use**.

Thanks for the tutorial!

**Comment by FeynmanDNA** [comment]
https://codelabs.developers.google.com/codelabs/firebase-web/index.html?index=..%2F..index#3

This is the link to the page

**Comment by nicolasgarnier** [comment]
Fixed thanks!
