### ISSUE TITLE
It doesn't show notifications Step 11

### ISSUE THREAD

**Issue by Josehdez96** [firebase/friendlychat-web#382]
I  don't exactly know where I should copy this part of the code 

POST /fcm/send HTTP/1.1
Host: fcm.googleapis.com
Content-Type: application/json
Authorization: key=YOUR_SERVER_KEY

{
  "notification": {
    "title": "New chat message!",
    "body": "There is a new message in FriendlyChat",
    "icon": "/images/profile_placeholder.png",
    "click_action": "http://localhost:5000"
  },
  "to":"YOUR_DEVICE_TOKEN"
}

I guess this is my problem, because I copied in firebase-messaging-sw-js and it doesn't show any notification... where should I copy that part of code? or what is my problem if this isn't?

**Comment by MRamGopal** [comment]
i am also in same problem

**Comment by medeirosjoaquim** [comment]
Same problem here. I can get the "Request permissions to show notifications" and the token.
I send the post request (using Postman in my case) and it goes ok:
`{
    "multicast_id": 4875602948128793166,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1549046634048635%e609af1cf9fd7ecd"
        }
    ]
}`

But no notification shows

**Comment by jhuleatt** [comment]
Looks like this question is for this step of the web codelab: https://codelabs.developers.google.com/codelabs/firebase-web/#10

The POST... text is just a description of what needs to be sent. Paste the cURL command in step 2 under **Send a notification to your device** into a terminal to run it

**Comment by jhuleatt** [comment]
I'm going to close this issue since I think I've answered the original question. Please comment if you'd like to reopen it

**Comment by sudhakar086** [comment]
same issue, here. @jhuleatt the github link does not solve the issue.
