### ISSUE TITLE
Uncaught TypeError: firebase.firestore is not a function

### ISSUE THREAD

**Issue by tcerven** [firebase/friendlychat-web#386]
I got this error on Step 5 when I first ran the server. I worked around by adding this line to index.html:

<script src="https://www.gstatic.com/firebasejs/5.7.2/firebase-firestore.js"></script>

**Comment by nicolasgarnier** [comment]
Sorry about that. It got fixed 12h ago at: https://github.com/firebase/friendlychat-web/commit/efb82fd72284adf669fc1eafff50adfbd9dc79a0

perhaps you checked out the code at an earlier time.
