### ISSUE TITLE
Step 10 - cleanup the tokens (Cloud Functions for Firebase): collection name wrong.

### ISSUE THREAD

**Issue by kakizaki** [firebase/friendlychat-web#388]
the collection name in tutorial is **messages**:  
cleanupTokens function in functions/index.js
```javascript
     // Cleanup the tokens who are not registered anymore.
     if (error.code === 'messaging/invalid-registration-token' ||
         error.code === 'messaging/registration-token-not-registered') {
       const deleteTask = admin.firestore().collection('messages').doc(tokens[index]).delete();
       tokensDelete.push(deleteTask);
     }
```

**messages** should be **fcmTokens**?
```javascript
     // Cleanup the tokens who are not registered anymore.
     if (error.code === 'messaging/invalid-registration-token' ||
         error.code === 'messaging/registration-token-not-registered') {
       const deleteTask = admin.firestore().collection('fcmTokens').doc(tokens[index]).delete();
       tokensDelete.push(deleteTask);
     }
```

Thanks for the tutorial!

**Comment by jhuleatt** [comment]
Hmm, yeah this looks like a bug in the sample code.

**Comment by jhuleatt** [comment]
Confirmed, the web app writes to the `fcmTokens` collection:

https://github.com/firebase/friendlychat-web/blob/a3d21675fcbf5e4c56eb67257658348484bcbf82/cloud-functions/public/scripts/main.js#L117

**Comment by kakizaki** [comment]
yes, the app writes device token to the `fcmTokens` collection. 
but `cleanupFunction` try to remove from messages collection.

https://github.com/firebase/friendlychat-web/blob/a3d21675fcbf5e4c56eb67257658348484bcbf82/cloud-functions/functions/index.js#L127

**Comment by djlauk** [comment]
The code snippet in the tutorial step itself still uses the wrong collection name: https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#9
