### ISSUE TITLE
Sign in option doesnt come at all , directly goes to chat ui and when we type the message a pop up comes saying "sign in first"

### ISSUE THREAD

**Issue by SubramanyaVompolu** [firebase/friendlychat-web#390]

**Comment by zephyr93** [comment]
Same thing happened to me....
the buttons were there in the source code, just hidden - here is the view source:
 <header class="mdl-layout__header mdl-color-text--white mdl-color--light-blue-700">
    <div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-grid">
      <div class="mdl-layout__header-row mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell--12-col-desktop">
        <h3><i class="material-icons">chat_bubble_outline</i> Friendly Chat</h3>
      </div>
      <div id="user-container">
        <div hidden id="user-pic"></div>
        <div hidden id="user-name"></div>
        <button hidden id="sign-out" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
          Sign-out
        </button>
        <button hidden id="sign-in" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
          <i class="material-icons">account_circle</i>Sign-in with Google
        </button>
      </div>
    </div>
  </header>

**Comment by KaLaUnlimited** [comment]
I am having the same issues. any luck:?

**Comment by jhuleatt** [comment]
This is intended behavior, described in more detail in [this step of the web codelab](https://codelabs.developers.google.com/codelabs/firebase-web/#6)
