### ISSUE TITLE
Syntax error on Async function. Function wont deploy

### ISSUE THREAD

**Issue by Zimdollar** [firebase/friendlychat-web#392]
I keep getting an "Unexpected (" error on this line
exports.addWelcomeMessages = functions.auth.user().onCreate(**async**(user) => {

**Comment by jhuleatt** [comment]
Sorry for the slow response - do you still need help? If so, can you please provide the full code for your addWelcomeMessages function?

I'm wondering if you're just missing a space after the `async` keyword: https://github.com/firebase/friendlychat-web/blob/6349961112f18c2d38b4536a2f22e8914f12c489/cloud-functions/functions/index.js#L30
