### ISSUE TITLE
Possible typo in step 7 

### ISSUE THREAD

**Issue by clfaulkner** [firebase/friendlychat-web#393]
In the followin line:
If your app is still being served, refresh your app in the browser. Otherwise, run `firebase serve` on the command line to start serving the app from http://localhost:5000, then open it in your browser.

`firebase serve` should be: `firebase serve --only hosting`.

In VS Code I get an `unexpected error` if I don't use --only hosting.

**Comment by vigneshwaran-sourirajalu** [comment]
it doesn't work either :(

**Comment by clfaulkner** [comment]
I haven't tried this outside of VS Code; it might work just fine in a console window.

**Comment by clfaulkner** [comment]
Oops!

**Comment by clfaulkner** [comment]
More oops! I'm batting 1000 on clicking the wrong button this morning.

**Comment by jhuleatt** [comment]
Fixed, thanks!
