### ISSUE TITLE
Incorrect step link

### ISSUE THREAD

**Issue by zobkiw** [firebase/friendlychat-web#394]
https://codelabs.developers.google.com/codelabs/firebase-web/#14 states under Next Steps:

Continue on to the Cloud Functions for Firebase codelab to learn how to use the Firebase SDK for Cloud Functions and add some backend tasks to your chat app. You can start directly on Step 5 of that codelab since you've already set up your Firebase project.

The link goes to https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#5 which is *actually* Step 6 due to 0-based steps.

**Comment by jhuleatt** [comment]
This is fixed! Thanks @zobkiw!
