### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by zobkiw** [firebase/friendlychat-web#395]
https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#6 contains the grammatically incorrect text:

This is what happens do above when using admin.initializeApp();

**Comment by jhuleatt** [comment]
Sorry, thought I had fixed this a while ago. Fixed! It now says:

> The Firebase Admin SDK can be configured automatically when deployed on a Cloud Functions environment or other Google Cloud Platform containers. This is what we do above when calling `admin.initializeApp();`
