### ISSUE TITLE
main.js:65 Uncaught TypeError: firebase.database is not a function

### ISSUE THREAD

**Issue by momisageek** [firebase/friendlychat-web#396]
The qwiklab tutorial has an error that does not load firebase.database

The solution code does not use firebase.database  --- it is using firebase.firestore.     Has the syntax changed so that database is now firestore?    

Following the QWIKLAB  exactly will throw this error and nothing works from step 7 onward.

**Comment by pwreng** [comment]
I have the same problem. Any progress?

**Comment by Jaagrav** [comment]
Please help, this problem is literally spoiling the prestige of firebase!!!F*ck!!!!

**Comment by jhuleatt** [comment]
@Jaagrav can you please post which codelab you're using? This repo is referenced by a number of codelabs.

**Comment by krishan1456** [comment]
I have also this problem with new libs.

<script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-app.js"></script>


<script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-analytics.js"></script>

<script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
        apiKey: "----------------",
        authDomain: "---------.firebaseapp.com",
        databaseURL: "https://---------.firebaseio.com",
        projectId: "----------",
        storageBucket: "---------.appspot.com",
        messagingSenderId: "-----------",
        appId: "----------------",
        measurementId: "-----------"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
    var database = firebase.database();
</script>

**Comment by samtstern** [comment]
@krishan1456 you'll need to add this dependency as well:

**firebase-database**
```
<script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-database.js"></script>
```

**Comment by joaquim-paul** [comment]
I have had this error in my console saying function.database is not an a function. The solution for this is to remove -app in the gstatic script. Like the one below
Initial <script src="https://www.gstatic.com/firebasejs/7.2.0/firebase.js"></script>
Hope it helps.

**Comment by girishgodage** [comment]
Even I also was facing the same issue. I have removed "-app" in the below script.


<script src="https://www.gstatic.com/firebasejs/7.2.0/firebase.js"></script>

After that it works fine

**Comment by theneurofunk** [comment]
Have a same problem! Plaese? help!

**Comment by Abhinav-Mani** [comment]
I also was facing the same issue. I have removed "-app" and changed to the below script.
<script src="https://www.gstatic.com/firebasejs/7.2.3/firebase.js"></script>
Now it works

**Comment by fademan01** [comment]
I don't know why google haven't fix this bug yet, its still happening in current version 7.9.0.

**Comment by soonbinan** [comment]
removing -app does the job but adding `<script src="https://www.gstatic.com/firebasejs/7.6.1/firebase-database.js"></script>` after  ` <script src="https://www.gstatic.com/firebasejs/7.10.0/firebase-app.js">` should fix the problem.

**Comment by rrahool** [comment]
> I have had this error in my console saying function.database is not an a function. The solution for this is to remove -app in the gstatic script. Like the one below
> Initial <script src="https://www.gstatic.com/firebasejs/7.2.0/firebase.js"></script>
> Hope it helps.

Thanks, it worked for me. 👍

**Comment by rrahool** [comment]
> @krishan1456 you'll need to add this dependency as well:
> 
> **firebase-database**
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/7.1.0/firebase-database.js"></script>
> ```

Thanks, it worked for me. 👍

**Comment by SlyCreator** [comment]
adding this worked for me

<script src="https://www.gstatic.com/firebasejs/7.15.3/firebase-database.js"></script>

**Comment by hirwahabakaramojules** [comment]
this helped me instead 
`<script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-database.js"></script>`

**Comment by Alfredo-Rojas** [comment]
I recommend using: "<script src="https://www.gstatic.com/firebasejs/7.15.3/firebase-database.js"></script>" because it works both in Development and Production !!

**Comment by Jaagrav** [comment]
> Please help, this problem is literally spoiling the prestige of firebase!!!F*ck!!!!

I take this back, I was a fool then, you just need to import the whole firebase library
```html
<script src="https://www.gstatic.com/firebasejs/7.15.3/firebase.js"></script>
```

And this definitely worked for me. You can do the above stuff as well in order to import specific firebase services but my method would basically import all services from firebase. However I'd suggest you to do what @hirwahabakaramojules did, that would import only the services you want to use, this would decrease the bundle size and make your stuff load faster.

```html
<script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-database.js"></script>
````

**Comment by Alfredo-Rojas** [comment]
I tried it but it doesn't work for me in production, it only works in development. That is why I am importing the whole package.

**Comment by Jaagrav** [comment]
Well if importing the whole package works, then I guess it's fine, it's not really noticeable that much, if you do it using react that's where you could probably make it work. Anyway happy coding!

**Comment by D99-1** [comment]
Removing   -app  worked for me, thx
