### ISSUE TITLE
function call in text does not match code

### ISSUE THREAD

**Issue by codesurgeon** [firebase/friendlychat-web#401]
In [step #7 of the Cloud Functions for Firebase](https://codelabs.developers.google.com/codelabs/firebase-cloud-functions/#7 ) codelab there's a typo in the subsection with the header _Adding welcome messages_. The first function call in the text following the headline reads `functions.auth().onCreate` where it should be `functions.auth.user().onCreate`.

The code in the following embedded code section is correct.

**Comment by jhuleatt** [comment]
thanks for the feedback! looks like this has been fixed
