### ISSUE TITLE
Time stamps error from Firebase

### ISSUE THREAD

**Issue by clfaulkner** [firebase/friendlychat-web#406]
Received the following error message when loading the page in the local server `Firebase serve`:

[2019-04-20T04:13:25.789Z]  @firebase/firestore: Firestore (5.9.1): 
  The timestampsInSnapshots setting now defaults to true and you no
  longer need to explicitly set it. In a future release, the setting
  will be removed entirely and so it is recommended that you remove it
  from your firestore.settings() call now.

This was generated by code in `main.js`, lines 360 & 361. It was corrected by commenting-out those 2 lines.

Perhaps a future version can update this item. It might be confusing to newbie dev's like myself. 
Although, I have to say, running the error to ground might actually be benefical from a learning perspective.

Thanks,
--Chris F.

**Comment by jhuleatt** [comment]
thanks for catching that, Chris!

**Comment by tempral** [comment]
is still there
