### ISSUE TITLE
Step 7 in codelab Test signing-in to the app failing

### ISSUE THREAD

**Issue by mmcguff** [firebase/friendlychat-web#409]
Browser:  Chrome
Browser version: 73.0.3683.103 (Official Build) (64-bit)
Operating system: MacOS
Operating system version: Version 10.14.4 (18E226)

## What steps will reproduce the problem:
1.  From either `/web` or `/web-start` run: `firebase use <projectId>`
2.  run:  `firebase serve`
3.  Click the Sign-In with Google link in the upper right hand corner.  ![image](https://user-images.githubusercontent.com/10658437/56705300-fff7ae00-66d5-11e9-80e1-66ef1613ef59.png)

## What is the expected result?
Should Log you into the the Friendly Chat using your Google Sign-In as per the tutorial test.  See [Test signing-in to the app](https://codelabs.developers.google.com/codelabs/firebase-web/?authuser=0#6)

## What happens instead of that?
Sign In fails with the following in the console:

nexttick.js:41 Uncaught Ki {code: "auth/operation-not-allowed", message: "The identity provider configuration is disabled."}code: "auth/operation-not-allowed"message: "The identity provider configuration is disabled.

## Please provide any other information below, and attach a screenshot if possible.
![image](https://user-images.githubusercontent.com/10658437/56705244-d179d300-66d5-11e9-9200-33f8d69f76a4.png)

I also attempted changing `<script src="/__/firebase/5.10.0/firebase-auth.js"></script>` to `5.9.0` to see if that would make a difference but I'm still getting the same issue.  Let me know what else I should try.  Thanks in advance.

**Comment by ijimaso** [comment]
## My details
I had the same problem.
I tried to downgrade node.js v6.11.5 optimized Firebase, but the problem didn't fixed.
I have reached [the stackoverflow page](https://stackoverflow.com/questions/55522640/the-identity-provider-configuration-is-not-found-react-native-firebase-authent).

## The Solution
You go to the Firebase console, and you enter Authentication at the left tab.
You go to sign-in provider, and choose Google.
And You **enable Authentication** by clicking the upper right hand button.
Then you will able to sign in with FriendlyChat!!

### The image
Sorry, Japanese ver!!<br>
<img width="580" alt="firebase-auth" src="https://user-images.githubusercontent.com/38425740/57021880-6a759480-6c68-11e9-8086-a517649eb8b4.PNG">

**Comment by jhuleatt** [comment]
This is covered in the codelab under the **Enable Google sign-in for Firebase Auth** header in [Step 3](https://codelabs.developers.google.com/codelabs/firebase-web/?authuser=0#2). If that doesn't solve it for you, please comment and I'll reopen.
