### ISSUE TITLE
Step 9 function 'blurOffensiveImages' triggered recursively

### ISSUE THREAD

**Issue by mila-mila** [firebase/friendlychat-web#424]
Hi,
I reached step 9 in the tutorial where function 'blurOffensiveImages' is run with the trigger:
.storage.object().onFinalize().
Later, the image is blurred and modified, which triggers onFinalize() again.. endlessly.

This could get really expensive for people who decide to go with Cloud Vision API. Luckily, I skipped this part and only tested the blurring.

I suggest the following (tested) modification of the code both on the github and in the tutorial text:

`// Checks if uploaded images are flagged as Adult or Violence and if so blurs them.
exports.blurOffensiveImages = functions.runWith({memory: '2GB'}).storage.object().onFinalize(
    async (object) => {
      const image = {
        source: {imageUri: `gs://${object.bucket}/${object.name}`},
      };

      //Checks if the image has been blured already, i.e. if message has 'moderated' field set to true
      const messageId = object.name.split(path.sep)[1];
      let doc = await admin.firestore().collection('messages').doc(messageId).get();
      if (doc.exists) {
        if (typeof doc.data().moderated !== 'undefined' && doc.data().moderated === true) {
          console.log('The image already blured');
          return;
        }
      } else {
        console.log('document not found');
      }

      // Check the image content using the Cloud Vision API.
      const batchAnnotateImagesResponse = await vision.safeSearchDetection(image);
      const safeSearchResult = batchAnnotateImagesResponse[0].safeSearchAnnotation;
      const Likelihood = Vision.types.Likelihood;
      if (Likelihood[safeSearchResult.adult] >= Likelihood.LIKELY ||
          Likelihood[safeSearchResult.violence] >= Likelihood.LIKELY) {
        console.log('The image', object.name, 'has been detected as inappropriate.');
        return blurImage(object.name);
      }
      console.log('The image', object.name, 'has been detected as OK.');
});`

I worked on windows, with friendlychat-web code, don't know if this applies to angular version.

Kind regards,
Mila

**Comment by nicolasgarnier** [comment]
Normally the image is only blurred if it is detected as inappropriate. Once Blurred the new image should not be detected as inappropriate anymore though so this breaks the loop. Did this behave differently for you?

If the blurred image is really still inappropriate it's acceptable to blur it again until it's not :)

**Comment by mila-mila** [comment]
Right, i knew there was something i missed. But then there are two checks,
which is ok if the image for some reason is still inappropriate.
You may disregard the issue..
Thanks
