### ISSUE TITLE
Set up your project's consent screen for Auth to work

### ISSUE THREAD

**Issue by sufood** [firebase/friendlychat-web#431]
Setting up Authentication is more complex than described in these instructions
You need another section covering the instructions here:
https://support.google.com/cloud/answer/6158849?hl=en
You need to set up your project's consent screen and request verification before authentication will work.

**Comment by jhuleatt** [comment]
Thanks for calling this out. Those steps aren't actually necessary. You can just add a support email in the Firebase console to get rid of this warning.

I added it as step 2 in the [quickstart repo](https://github.com/firebase/quickstart-js/blob/master/auth/README.md#getting-started), but forgot to add to this repo

**Comment by jhuleatt** [comment]
I've updated the codelab and removed the "optional" wording around the "add a support email" [step](https://codelabs.developers.google.com/codelabs/firebase-web/#2).

It now says "Set the public-facing name of your app to Friendly Chat and choose a Project support email from the dropdown menu."
