### ISSUE TITLE
the order of chat is not right when chat with others 

### ISSUE THREAD

**Issue by ssqarni** [firebase/friendlychat-web#433]
**Describe the bug**
the order of chat is not right when chat with others, for example:
ME: hello
other : Hi
ME: how are you
..... when other responds "Im fine", it goes above "how are you"

**To Solve**

1. Go to 'friendlychat-web/web-start/public/scripts/'
2. Click on 'main.js'
3. Scroll down to 'function displayMessage'
4. See error "if (time && time > timestamp)" 
5- REPLACE the second variable "time" to any global variable for example . 
if (time && lastTimeStamp > timestamp)
6- Define the global variable "lastTimeStamp" inside the function loadMessages() , for example
      after:
        displayMessage(change.doc.id, message.timestamp, message.name,
                       message.text, message.profilePicUrl, message.imageUrl);
     add this code:
        lastTimeStamp= message.timestamp.toString();
Dont forget to declare lastTimeStamp variable
       

**Expected behavior**
I tested it , and it is working

**Additional context**
is there a better way?

**Comment by jhuleatt** [comment]
Thanks for catching this @ssqarni! I have a fix in the works.
