### ISSUE TITLE
Step 14 - "Collect performance data" Requires an Additional Step

### ISSUE THREAD

**Issue by mgmgpyaesonewin** [firebase/friendlychat-web#444]
[REQUIRED] Codelab info
Firebase Web Codelab

[REQUIRED] Project setup
friendlychat-web/web-start

[REQUIRED] Describe the problem
In main.js, it has the step to enable performance via showing
```
// TODO: Enable Firebase Performance Monitoring.
```
But what to enable is not included in codelab. It required to add
```
var perf = firebase.performance();
```
But not included in codelab. Without enabling this, I cannot find logging.

[Optional] Suggested fix
Updated text to

add this line in line number `371`.
```
var perf = firebase.performance();
```

Set to check that Performance Monitoring is logging data

**Comment by jhuleatt** [comment]
Nice catch @mgmgpyaesonewin! I've updated step 14 of the codelab to include that: https://codelabs.developers.google.com/codelabs/firebase-web/#13
