### ISSUE TITLE
Step 7 - Buttons hidden within HTML

### ISSUE THREAD

**Issue by JoeEarly** [firebase/friendlychat-web#458]
**Describe the bug**
Sign In/Out buttons have 'hidden' property in place on the 'web-start' project so are not viewable when working through Step 7. 

**To Reproduce**
1. Follow steps to Step 7
2. Open 'web-start/public/index.html'
3. Scroll down to 'Line 65'

` <div id="user-container">
        <div hidden id="user-pic"></div>
        <div hidden id="user-name"></div>
        <button hidden id="sign-out" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
          Sign-out
        </button>
        <button hidden id="sign-in" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-color-text--white">
          <i class="material-icons">account_circle</i>Sign-in with Google
        </button>
      </div>`

**Expected behavior**
Should not have hidden attribute in place 
![Screenshot 2019-08-29 at 12 36 46](https://user-images.githubusercontent.com/5208459/63937200-cbb44580-ca59-11e9-80bb-ecc66941a0cc.png)

**Comment by samtstern** [comment]
@Joe thanks for the report!  @jhuleatt can you try to reproduce?

**Comment by nickcollie** [comment]
I can reproduce this.
I'd guess there is some js that is intended to remove the class from either the in or out buttons??? Depending on which is appropriate.  That does not seem to be running ...

**Comment by nickcollie** [comment]
Yup, if I fire off authStateObserver(user) at the bottom of the page then the buttons appear. But the state does not appear to be initialised correctly.

**Comment by jhuleatt** [comment]
Thanks for the report @JoeEarly and sorry for the delay! I've fixed this in #477
