### ISSUE TITLE
Unable to setup SDK 

### ISSUE THREAD

**Issue by JamesVanWaza** [firebase/friendlychat-web#463]
### [REQUIRED] Codelab info

I am trying to complete the following tutorial https://codelabs.developers.google.com/codelabs/firebase-web/#5

### [REQUIRED] Project setup

https://github.com/firebase/friendlychat-web/

### [REQUIRED] Describe the problem
1. Unable to add Firebase SDK
2. Cloud Functions requires the firebase-functions even though I see it installed in my `package.json` file

However, I keep getting the following errors, even though, I have added the following examples on my page. See the screenshots attached. 

My Firebase version is **7.6.1**
My Node version is **12.12.0**

[![enter image description here][1]][1]

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/21jfu.png
  [2]: https://i.stack.imgur.com/6wCcP.png

<img width="1025" alt="Screenshot 2019-10-21 19 07 58" src="https://user-images.githubusercontent.com/4000076/67249563-1c329880-f436-11e9-81c9-2d18bf140bab.png">

<img width="1527" alt="Screenshot 2019-10-21 19 10 18" src="https://user-images.githubusercontent.com/4000076/67249657-716eaa00-f436-11e9-8ec1-541088709cee.png">

<img width="1331" alt="Screenshot 2019-10-21 19 24 35" src="https://user-images.githubusercontent.com/4000076/67250222-906e3b80-f438-11e9-9e3c-ee6eecb18b63.png">
<img width="1196" alt="Screenshot 2019-10-21 19 25 16" src="https://user-images.githubusercontent.com/4000076/67250223-906e3b80-f438-11e9-9a8d-e08d6dc083d7.png">

**Comment by bsachin207** [comment]
Are you using Windows or Linux? I think you need node 8.0 rather than 12.X

**Comment by JamesVanWaza** [comment]
I tried with Node '12' but still getting the unable to find SDK error.

**Comment by bsachin207** [comment]
Did you try with node 8.0?

**Comment by JamesVanWaza** [comment]
Not yet.

**Comment by bsachin207** [comment]
Did you run `firebase login` and `firebase init` in that web-start directory.

**Comment by samtstern** [comment]
@JamesVanWaza it looks like you're having issues with Cloud Functions from `firebase serve`.  But this codelab only needs the hosting server, so you should be able to workaround this using `firebase serve --only hosting`.

Does that help?

**Comment by JamesVanWaza** [comment]
@bsachin207 @samtstern 
First I updated the node version to 12 on 'package.json'
Secondly, `firebase serve` shows the following

I am still getting the following error. 

Is there a video showing how to fix it? 

<img width="1680" alt="Screenshot 2019-11-08 10 54 50" src="https://user-images.githubusercontent.com/4000076/68490174-8446f400-0216-11ea-8e62-5f409cb7fced.png">

2. Is this how the scripts should be placed 

<img width="1591" alt="Screenshot 2019-11-08 10 58 00" src="https://user-images.githubusercontent.com/4000076/68490239-a5a7e000-0216-11ea-9732-6f5e0a9deb61.png">

<img width="825" alt="Screenshot 2019-11-08 10 55 27" src="https://user-images.githubusercontent.com/4000076/68490176-8446f400-0216-11ea-8dc2-7c4e2be26f1b.png">

**Comment by samtstern** [comment]
@JamesVanWaza in one screenshot I see you're using Firebase SDKs version `7.2.1` and in other I see `6.4.0`.  Why the switch?  Are those different files?

**Comment by JamesVanWaza** [comment]
@samtstern That's the current update so I updated. It shows the new version is `7.2.3` - https://github.com/firebase/friendlychat-web/pull/464/files

**Comment by JamesVanWaza** [comment]
@samtstern how do I fix this error now?

<img width="1468" alt="Screenshot 2019-11-10 09 56 35" src="https://user-images.githubusercontent.com/4000076/68546187-f13ac500-03a1-11ea-8813-1b0e4f8bf563.png">

**Comment by jhuleatt** [comment]
@JamesVanWaza please run `firebase serve --only hosting` instead of `firebase serve` and see if that works. More context in [Sam's comment above](https://github.com/firebase/friendlychat-web/issues/463#issuecomment-551176871)

**Comment by JamesVanWaza** [comment]
I was able to get it to work. 

Very much appreciated to @jhuleatt @samtstern @bsachin207
