### ISSUE TITLE
Update folders at Angular 8

### ISSUE THREAD

**Issue by BrayanVG** [firebase/friendlychat-web#473]
**Is your feature request related to a problem? Please describe.**
They could update the folder from Angular to Angular 8 or 9, since it is not working and these folders do not have the same style and operation as the web
**Describe the solution you'd like**

**Comment by samtstern** [comment]
@BrayanVG sorry we never got back to you here, but this description is not enough information to know what's going on or help you debug.  If you still need help please file a new issue include code, logs, etc.
