### ISSUE TITLE
Sign In button not showing after deployment or in local host

### ISSUE THREAD

**Issue by Sanjit1** [firebase/friendlychat-web#475]
### Codelab info

https://codelabs.developers.google.com/codelabs/firebase-web/

###  Project setup

Using the web start directory

###  Describe the problem

For some reason when I run the codelab locally, the sign-in button is non-functional, and after looking through some issues here, I saw that just finishing the codelab and deploying might be the solution, but when I deployed, I run into the same issue.
It's running here:
https://csp-chat-ec176.firebaseapp.com/

**Comment by jhuleatt** [comment]
The function that makes the button visible is here: https://github.com/firebase/friendlychat-web/blob/4b825e4ca3e4a5342ea8a4642068e0a175d762ac/web-start/public/scripts/main.js#L111

That function won't get called until you follow the "Track the authentication state" step in the codelab.

**Comment by jhuleatt** [comment]
Right now that button defaults to being invisible. Maybe we should change that so that the codelab is a bit easier to follow

**Comment by Sanjit1** [comment]
Hmm.  I did follow the codelab step to step, although I did struggle on the auth part because I was not sure what I was supposed to do at GCP.

**Comment by jhuleatt** [comment]
Can you please elaborate on where you got stuck with GCP? Was it setting up a support email for Google Sign In?

**Comment by jhuleatt** [comment]
I've updated the codelab source so that the auth button is visible from the start. If you're still stuck on GCP stuff, please open a separate issue so we can focus on that. Thanks!

**Comment by Sanjit1** [comment]
Thank you!
