### ISSUE TITLE
photourl is get nullpointerexception

### ISSUE THREAD

**Issue by imsabin** [firebase/friendlychat-web#51]
getphotourl is getting nullpointerexception in android.

**Comment by XphantasmaX** [comment]
It's not in the tutorial, but turns out that on step #9 you must add and "If" statement in the line where you index the friendlymessage:

```java
if (friendlyMessage.getText() != null) {
      // write this message to the on-device index
      FirebaseAppIndex.getInstance().update(getMessageIndexable(friendlyMessage));
}
```

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#18
