### ISSUE TITLE
Friendly chat developer tutorial section 6

### ISSUE THREAD

**Issue by el-samiyel** [firebase/friendlychat-web#69]
Hi, 
Regarding "https://codelabs.developers.google.com/codelabs/firebase-android/#5"
When I reach stage 6 - "Then add a new case to onOptionsItemSelected() to handle the sign out button:"

`@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.sign_out_menu:
                mFirebaseAuth.signOut();
                Auth.GoogleSignInApi.signOut(mGoogleApiClient);
                mUsername = ANONYMOUS;
                startActivity(new Intent(this, SignInActivity.class));
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }`

line:
`mFirebaseAuth.signOut();` shows error "Unreachable statment".

Why is this?

Many Thanks

**Comment by harshLFC** [comment]
Don't know

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#17
