### ISSUE TITLE
Can't open the project.

### ISSUE THREAD

**Issue by ghost** [firebase/friendlychat-web#78]
I can't seem to open the project. Why is that?
I am using Android studio 2.1.3 with gradle version of 2.1.3

**Comment by samtstern** [comment]
@geraldjaydlagarto we will need more information to help you.  What exactly is going wrong?  What steps did you take?

**Comment by carlosjs23** [comment]
I'm also having this problem. The project never finish to build gradle.

![error-img](https://i.gyazo.com/fcd4958a7365b43c7387a7216c60e721.png)

Android Studio version: 2.2.2

Thanks you.

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#16
