### ISSUE TITLE
Chat Application - Sign In Problem in Real Device

### ISSUE THREAD

**Issue by dylanver2** [firebase/friendlychat-web#82]
My app is working with the emulator but not in real device. I installed the signed APK and at the login screen i am stucked with the sign in button. Select an account and nothing happens. 

I tried to connect my device via USB tested and it worked. App is currently working on my phone just because I connected it to USB and run it for debugging. Does this mean there's something wrong with my APK?

**Comment by kroikie** [comment]
Could you double check that the SHA1 for the keystores you are using for signing are all added to the Firebase console?

It could be that when connected via USB or running on the emulator you are using the debug keystore for signing which you have added to the Firebase console and thus the app is working. If you are signing with another keystore when you are generating the "signed APK" it will not work if you have not added the SHA1 for the other keystore.

**Comment by CreaRo** [comment]
@dylanver2  Have a look [here](https://github.com/firebase/friendlychat/issues/11). I spent hours on this before I could get it to work.

**Comment by kroikie** [comment]
This issue was moved to firebase/friendlychat-android#15
